use_frameworks!

platform :ios, '15.6'

target 'AKPageFlipperCollectionView_Example' do
  pod 'AKPageFlipperCollectionView', :path => '../'

  target 'AKPageFlipperCollectionView_Tests' do
    inherit! :search_paths

    
  end
end
